### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by milenkocvijic** [frywer/custom_tables#15]
I get this message during install...
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: database_cleaner (>= 0) and database_cleaner (~> 1.6.1). Bundler cannot continue.

 #  from /opt/bitnami/apps/redmineplusagile/htdocs/plugins/custom_tables/Gemfile:6
 #  -------------------------------------------
 #    gem 'poltergeist'
 >    gem 'database_cleaner', '~> 1.6.1'
 #    gem 'rspec-retry'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /opt/bitnami/apps/redmineplusagile/htdocs/Gemfile:99
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

**Comment by frywer** [comment]
Hi @milenkocvijic 
I have removed gem 'database_cleaner' from the plugin, now it should be OK
