### ISSUE TITLE
Not able to insert field value with API

### ISSUE THREAD

**Issue by MuhaoSZ** [frywer/custom_tables#24]
Hi, 
I try to use Rest API to insert a new row to a custom table. 
After I sent the http request, a new row do inserted to my custom table, but the field value was not. Please see below:

```
curl -X POST -H "Content-Type: application/json" -H "X-Redmine-API-Key: 8b506638580e4918f9249ac622cd835b30a63e86" -d '{"custom_entity": {"custom_table_id":8, "issue_id":35, "external_names":{"HTS":"xxxxxx"}}}' http://redmine.devops.wq/custom_entities.json
{"id":89,"HTS":"","issue_id":35,"custom_table_id":8}
```

I wanted to assign "xxxxxx" to column "HTS" when the row was created. A new row was created but "xxxxxx" was not assigned to column "HTS", which kept blank.
Is there any thing incorrect I did?  Can you help figure out where the problem is?

Thanks

**Comment by MuhaoSZ** [comment]
I figure it out. Use "external_values" instead of "external_names".

**Comment by ashrafalzyoud** [comment]
The users see the table value or not ?!
@MuhaoSZ
