### ISSUE TITLE
Field format "User"

### ISSUE THREAD

**Issue by mpauz** [frywer/custom_tables#4]
There is possibility to add field format "User" with drop-down list of all users OR users inherited with project/issue?

**Comment by andreabonadei** [comment]
+1 Not that I am aware of. I'm looking forward to this being implemented.

**Comment by frywer** [comment]
https://github.com/frywer/custom_tables/pull/12

**Comment by frywer** [comment]
@andreabonadei @mpauz thanks for the feedback. PR is merged to master
