### ISSUE TITLE
Contents of the values are shown only if the user has admin rights

### ISSUE THREAD

**Issue by frywer** [frywer/custom_tables#40]
Hi.
In the custom_tables (redmine) plugin, the contents of the values are
shown only if the user has admin rights.

The problem is reproduced on versions 4.2.8 and 4.2.9.

**Comment by frywer** [comment]
duplicated #38

**Comment by ashrafalzyoud** [comment]
Can u check plz
If I have tow group working in the same table

Are every one show all the data
Or every group see her work
